# Generated by Django 3.0.4 on 2020-08-11 02:30

from django.db import migrations, models
import product_category.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default='abc', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product_category.models.upload_image_path)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
