# Generated by Django 3.0.4 on 2020-04-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='Email',
            new_name='email',
        ),
    ]
