# Generated by Django 3.0.4 on 2020-10-06 07:06

import blog_category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default='blog', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog_category.models.upload_image_path)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
