# Generated by Django 3.0.4 on 2020-10-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_category', '0001_initial'),
        ('blogs', '0002_blog_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_category.Categories'),
        ),
    ]
